AWSTemplateFormatVersion: 2010-09-09
Parameters:
  AmiParameter:
    Default:  ami-034ef92d9dd822b08
    Description: The AMI Id to use for the instance
    Type: String
  InstanceProfileParameter:
    Description:  The name of the IAM role the EC2 Instance should user
    Type: String
  InstanceTypeParameter:
    Default:  t2.micro
    Description: The type of instance to create
    Type: String
Resources:
  IntegrationVPC:
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: 'false'
      EnableDnsSupport: 'false'
      InstanceTenancy: 'default'
      Tags:
        - 
          Key: Name
          Value: Int-VPC
        -
          Key: Environment
          Value: Integration
    Type: AWS::EC2::VPC
  IntegrationInternetGateway:
    Properties:
      Tags:
        -
          Key: Name
          Value:  Int-InternetGateway
        -
          Key:  Environment
          Value:  Integration
    Type: AWS::EC2::InternetGateway
  IntegrationSecurityGroup:
    Properties:
      GroupDescription:  Group to allow HTTP and SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: 22
          ToPort: 22
        - IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: 80
          ToPort: 80
        - IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: 443
          ToPort: 443
      VpcId:  !Ref IntegrationVPC
    Type: AWS::EC2::SecurityGroup
  IntegrationSubnet:
    DependsOn: IntegrationVPC
    Properties:
      CidrBlock:  10.0.0.0/16
      MapPublicIpOnLaunch: True
      Tags:
        -
          Key:  Environment
          Value:  Integration
      VpcId:  !Ref IntegrationVPC
    Type: 'AWS::EC2::Subnet'
  IntegrationVPCGatewayAttachment:
    Properties:
      InternetGatewayId: !Ref IntegrationInternetGateway
      VpcId:  !Ref IntegrationVPC
    Type: AWS::EC2::VPCGatewayAttachment
  IntegrationVPCRouteTable:
    Properties:
      Tags:
        -
          Key:  Environment
          Value:  Integration
        -
          Key:  Name
          Value:  IntegrationVPCRouteTable
      VpcId:  !Ref IntegrationVPC
    Type: AWS::EC2::RouteTable
  IntegrationInternetGatewayRoute:
    DependsOn: IntegrationInternetGateway
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref IntegrationInternetGateway
      RouteTableId: !Ref IntegrationVPCRouteTable
    Type: AWS::EC2::Route
  IntegrationSubnetRouteTableAssociation:
    Properties:
      SubnetId: !Ref IntegrationSubnet
      RouteTableId: !Ref IntegrationVPCRouteTable
    Type: AWS::EC2::SubnetRouteTableAssociation
  WebServer:
    Properties:
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 8
            VolumeType: gp2
      IamInstanceProfile: !Ref InstanceProfileParameter
      InstanceType: !Ref InstanceTypeParameter
      ImageId: !Ref AmiParameter
      SecurityGroupIds: 
        - !Ref IntegrationSecurityGroup
      SubnetId: !Ref IntegrationSubnet
      Tags:
        - 
          Key:  Environment  
          Value: Integration
        - 
          Key:  Name  
          Value: IntegrationWebServer
    Type: AWS::EC2::Instance
Outputs:
  PublicIp:
    Description: Server's PublicIp Address
    Value:
      Fn::GetAtt:
        - WebServer
        - PublicIp