AWSTemplateFormatVersion: 2010-09-09
Parameters:
  AmiParameter:
    Default:  ami-034ef92d9dd822b08
    Description: The AMI Id to use for the instance
    Type: String
  InstanceTypeParameter:
    Default:  t2.micro
    Description: The type of instance to create
    Type: String
  VpcParameter:
    Description: The Id of the VPC to create the resources in
    Type: String
Resources:
  IntegrationSubnet:
    Properties:
      CidrBlock:  172.31.48.0/20
      MapPublicIpOnLaunch: True
      Tags:
        -
          Key:  Environment
          Value:  Integration
      VpcId:  !Ref VpcParameter
    Type: 'AWS::EC2::Subnet'
  IntegrationSecurityGroup:
    Properties:
      GroupDescription:  Group to allow HTTP and SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: 22
          ToPort: 22
        - IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: 80
          ToPort: 80
      VpcId:  !Ref VpcParameter
    Type: AWS::EC2::SecurityGroup
  WebServer:
    CreationPolicy:
      ResourceSignal:
        Timeout:  PT5M
    Properties:
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 250
      IamInstanceProfile: EC2-CodeDeploy-InstanceProfile
      InstanceType: !Ref InstanceTypeParameter
      ImageId: !Ref AmiParameter
      KeyName: EC2-DevTest
      SecurityGroupIds: 
        - !Ref IntegrationSecurityGroup
      SubnetId: !Ref IntegrationSubnet
      Tags:
        - 
          Key:  Environment  
          Value: Integration
        - 
          Key:  Name  
          Value: IntegrationWebServer
      UserData:
        Fn::Base64: |
          #!/bin/bash
          sudo yum update -y
          sudo amazon-linux-extras install nginx1
          sudo service nginx start
          sudo yum install ruby
          sudo yum install wget
          echo $HOME
          sudo mkdir /home/cfn-install
          cd /home/cfn-install
          sudo wget https://aws-codedeploy-eu-west-2.s3.eu-west-2.amazonaws.com/latest/install
          sudo chmod +x ./install
          sudo ./install auto
          sudo rpm -Uvh https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm
          sudo yum install aspnetcore-runtime-6.0 -y
          /opt/aws/bin/cfn-signal -e 0 --stack Integration --resource WebServer --region eu-west-2
    Type: AWS::EC2::Instance
Outputs:
  PublicIp:
    Description: Server's PublicIp Address
    Value:
      Fn::GetAtt:
        - WebServer
        - PublicIp