AWSTemplateFormatVersion: '2010-09-09'
Description:  Lambda function for ImageColourSwap
Resources:
  ICSProcessingFunction:
    Properties:
      Code:
        S3Bucket: artifactstore-mk-test
        S3Key:  ImageColourSwapLambda
      Handler:  Lambda::ImageColourSwap.Lambda.Program::Handler
      MemorySize: 512
      Role: arn:aws:iam::267855555195:role/service-role/CodePipelineUpdateLambda-role-hty0oci1
      Runtime:  dotnet6
      Timeout:  30
    Type: AWS::Lambda::Function
  ICSLambdaPermission:
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref ICSProcessingFunction
      Principal:  'apigateway.amazonaws.com'
    Type: 'AWS::Lambda::Permission'