AWSTemplateFormatVersion: 2010-09-09

Parameters:
  AmiParameter:
    Default:  ami-034ef92d9dd822b08
    Description: The AMI Id to use for the instance
    Type: String
  InstanceProfileParameter:
    Description:  The name of the IAM role the EC2 Instance should user
    Type: String
  InstanceTypeParameter:
    Default:  t2.micro
    Description: The type of instance to create
    Type: String

Resources:
  InternetGateway:
    Properties:
      Tags:
        -
          Key:  Environment
          Value:  Integration
        -
          Key: Name
          Value:  InternetGateway
    Type: AWS::EC2::InternetGateway

  InternetGatewayRoute:
    DependsOn: InternetGateway
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref VPCRouteTable
    Type: AWS::EC2::Route

  KeyPair:
    Properties:
      KeyName:  IntegrationWebServerKeyPair
      Tags:
        -
          Key:  Environment
          Value:  Integration
        -
          Key: Name
          Value:  WebServerKeyPair
    Type: AWS::EC2::KeyPair

  SecurityGroup:
    Properties:
      GroupDescription:  Group to allow HTTP and SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: 22
          ToPort: 22
        - IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: 80
          ToPort: 80
        - IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: 443
          ToPort: 443
      Tags:
        -
          Key:  Environment
          Value:  Integration
        -
          Key: Name
          Value:  SecurityGroup
      VpcId:  !Ref VPC
    Type: AWS::EC2::SecurityGroup

  Subnet:
    DependsOn: VPC
    Properties:
      CidrBlock:  10.0.0.0/16
      MapPublicIpOnLaunch: True
      Tags:
        -
          Key:  Environment
          Value:  Integration
        -
          Key: Name
          Value:  Subnet
      VpcId:  !Ref VPC
    Type: 'AWS::EC2::Subnet'

  SubnetRouteTableAssociation:
    Properties:
      SubnetId: !Ref Subnet
      RouteTableId: !Ref VPCRouteTable
    Type: AWS::EC2::SubnetRouteTableAssociation

  VPC:
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: 'false'
      EnableDnsSupport: 'false'
      InstanceTenancy: 'default'
      Tags:
        -
          Key: Environment
          Value: Integration
        - 
          Key: Name
          Value: VPC
    Type: AWS::EC2::VPC
  
  VPCGatewayAttachment:
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId:  !Ref VPC
    Type: AWS::EC2::VPCGatewayAttachment
    
  VPCRouteTable:
    Properties:
      Tags:
        -
          Key:  Environment
          Value:  Integration
        -
          Key:  Name
          Value:  VPCRouteTable
      VpcId:  !Ref VPC
    Type: AWS::EC2::RouteTable

  WebServer:
    Properties:
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 8
            VolumeType: gp2
      IamInstanceProfile: !Ref InstanceProfileParameter
      InstanceType: !Ref InstanceTypeParameter
      ImageId: !Ref AmiParameter
      KeyName:  !Ref KeyPair
      SecurityGroupIds: 
        - !Ref SecurityGroup
      SubnetId: !Ref Subnet
      Tags:
        - 
          Key:  Environment  
          Value: Integration
        - 
          Key:  Name  
          Value: IntegrationWebServer
    Type: AWS::EC2::Instance

Outputs:
  PublicIp:
    Description: Server's PublicIp Address
    Value:
      Fn::GetAtt:
        - WebServer
        - PublicIp